### ISSUE TITLE
Output to Rd

### ISSUE THREAD

**Issue by hadley** [r-lib/commonmark#1]
How hard would it be? Then I could use it in roxygen

**Comment by jeroen** [comment]
Can you give an example of what the conversion you have in mind? Rd requires a specific structure with `\title{}`, `\description{}`, `\details{}`, etc. What would this look like in markdown?

**Comment by hadley** [comment]
I was thinking just for inline rd, like stuff you'd put in the details etc.

**Comment by jeroen** [comment]
OK. I guess if we can map out how the markdown types (`p`, `h1`-`h5`, `ol`, `ul`, `code`, etc) are represented in Rdoc then it shouldn't be too difficult to write a converter.

**Comment by hadley** [comment]
Yeah, I think it's mostly those (and maybe not even headings), strong and emph, definition lists (if that's in commonmark, can't remember), code blocks (-> preformatted) and tables.

**Comment by jeroen** [comment]
See also https://github.com/klutometis/roxygen/issues/365.

**Comment by gaborcsardi** [comment]
Oh, I just saw this. I guess this is exactly what maxygen does.
