### ISSUE TITLE
target="_blank" not being parsed correctly

### ISSUE THREAD

**Issue by boshek** [r-lib/commonmark#19]
👋 thanks for this amazing package. It enables so much. This might be an upstream issue but I thought to bring it here first. 

`commonmark::markdown_html` doesn't seem to parse markdown correctly for links that open in a new tab. 

For example `commonmark::markdown_html` generates this:

```{r}
commonmark::markdown_html("[RStudio](https://www.rstudio.com/){target='_blank'}")
```

```html
<p><a href=\"https://www.rstudio.com/\">RStudio</a>{target='_blank'}</p>
```

When I think this is what it should generate:

```html
<p><a href="https://www.rstudio.com" target="_blank">RStudio</a></p>
```

**Comment by jeroen** [comment]
I think attributes are [not supported](https://github.com/commonmark/commonmark-spec/pull/105) in the commonmark specification, and also not by any GFM extension. For example if I use your example markdown code in a github issue, it is also not parsed:

[RStudio](https://www.rstudio.com/){target='_blank'}

So I am afraid this is out of scope for commonmark.

**Comment by boshek** [comment]
Got it. Thanks for the quick response.
