### ISSUE TITLE
footnote XML output contains `<<unknown>>` tags

### ISSUE THREAD

**Issue by zkamvar** [r-lib/commonmark#23]
(edit: not sure how the reprex lost its formatting, but I fixed it)

The new `footnotes` feature might be useful for us at {tinkr}, but I'm not sure how to parse them as each footnote contains identical tags. 

from: https://github.com/ropensci/tinkr/issues/92#issuecomment-1479684407

```r
txt <- c("a statement[^1][^2]\n", "[^1]: this is true", "[^2]: this is false")
commonmark::markdown_xml(txt, footnotes = TRUE) |> writeLines()
#> <?xml version="1.0" encoding="UTF-8"?>
#> <!DOCTYPE document SYSTEM "CommonMark.dtd">
#> <document xmlns="http://commonmark.org/xml/1.0">
#>   <paragraph>
#>     <text xml:space="preserve">a statement</text>
#>     <<unknown> />
#>     <<unknown> />
#>   </paragraph>
#>   <<unknown>>
#>     <paragraph>
#>       <text xml:space="preserve">this is true</text>
#>     </paragraph>
#>   </<unknown>>
#>   <<unknown>>
#>     <paragraph>
#>       <text xml:space="preserve">this is false</text>
#>     </paragraph>
#>   </<unknown>>
#> </document>
```

<sup>Created on 2023-03-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jeroen** [comment]
Ew that's weird. Posted it upstream here: https://github.com/github/cmark-gfm/issues/316

**Comment by zkamvar** [comment]
I've added a potential fix for this in https://github.com/github/cmark-gfm/pull/362, but I'm not sure how active the maintainers are there.

**Comment by yihui** [comment]
I feel there is no hope that they would ever merge the fix upstream. @jeroen Do you think it will be easy enough to apply @zkamvar's patch to the **commonmark** R package here? Of course, I mean in a maintainable way (e.g., `git apply` after pulling `cmark-gfm`), not just as a one-time manual job.

**Comment by jeroen** [comment]
Yes we can do this. It looks like the upstream project is stale, sadly.

**Comment by jeroen** [comment]
Can you confirm your issue has been fixed now?

**Comment by jeroen** [comment]
Can you confirm your issue has been fixed? Could you maybe help me by adding a unit test to this package to ensure we do not regress in the future?

**Comment by zkamvar** [comment]
Thank you! I'll submit a PR with the tests by the end of the week 🤞🏽

**Comment by zkamvar** [comment]
And I have confirmed this works:

``` r
txt <- c("a statement[^1][^2]\n", "[^1]: this is true", "[^2]: this is false")
commonmark::markdown_xml(txt, footnotes = TRUE) |> writeLines()
#> <?xml version="1.0" encoding="UTF-8"?>
#> <!DOCTYPE document SYSTEM "CommonMark.dtd">
#> <document xmlns="http://commonmark.org/xml/1.0">
#>   <paragraph>
#>     <text xml:space="preserve">a statement</text>
#>     <fnref id="fnref-1" destination="fn-1" />
#>     <fnref id="fnref-2" destination="fn-2" />
#>   </paragraph>
#>   <fn id="fn-1">
#>     <paragraph>
#>       <text xml:space="preserve">this is true</text>
#>     </paragraph>
#>   </fn>
#>   <fn id="fn-2">
#>     <paragraph>
#>       <text xml:space="preserve">this is false</text>
#>     </paragraph>
#>   </fn>
#> </document>
```

<sup>Created on 2024-10-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by yihui** [comment]
I think I still need another patch (https://github.com/github/cmark-gfm/issues/314), otherwise there will be no way for me to identify footnotes in LaTeX output or post-process it to turn footnotes into `\footnote{}`. I'll take a closer look and open a new issue. Thanks!

P.S. I've also verified that the XML issue has been fixed.

**Comment by jeroen** [comment]
Should I apply this patch as well? https://github.com/github/cmark-gfm/pull/362
