### ISSUE TITLE
subscript text is converted to strikethrough

### ISSUE THREAD

**Issue by zkamvar** [r-lib/commonmark#25]
I noticed this in https://github.com/ropensci/tinkr/issues/99, but subscript text (at least with pandoc markdown) is converted to strikethrough (with two `~`) on roundtrip between markdown -> XML -> markdown

``` r
commonmark::markdown_commonmark("H~2~O", extensions = TRUE)
#> [1] "H~~2~~O\n"
```

<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jeroen** [comment]
This looks like a bug in cmark, can you report in in https://github.com/github/cmark-gfm ?

**Comment by zkamvar** [comment]
It appears that this is a feature, not a bug 😞:  https://github.com/github/cmark-gfm/issues/71#issuecomment-373170209

**Comment by jeroen** [comment]
Ok so there is nothing i can do :/

**Comment by zkamvar** [comment]
It turns out there was a fix for this and that was to set the `CMARK_OPT_STRIKETHROUGH_DOUBLE_TILDE` option. I've opened #31 to address it.
