### ISSUE TITLE
Some sort of abstract representation?

### ISSUE THREAD

**Issue by richfitz** [r-lib/commonmark#4]
Motivated by a particular use I have, but presumably there's some sort of intermediate representation available in commonmark?  Any chance of exposing that through R so that custom renderers can be written?

Thinking of something that could render markdown to marked up text using crayon in the terminal...

But perhaps I'm way off how this actually works under the hood.

**Comment by jeroen** [comment]
Yes internally it is just a syntax tree, and supposedly you can easily implement custom rendering formats in C. Although I think in practice it might be easier to get the syntax tree in xml format and go from there in R using xpath techniques and such.

**Comment by richfitz** [comment]
Fair enough, though I have an aversion to XML (and I see xml2 is off CRAN temporarily so I can't even try that - seriously WTF was that about?).  R could do with a really nice tree data structure.

**Comment by jeroen** [comment]
I think going via xml is the best approach for reading and manipulating the syntax tree. Gabor has a nice package [maxygen](https://github.com/gaborcsardi/maxygen) which uses commonmark + xml2 to support inline markdown for roxygen blocks. Closing this for now.
