### ISSUE TITLE
Text after a bullet list

### ISSUE THREAD

**Issue by jennybc** [r-lib/commonmark#7]
I'm having trouble with text after a bullet list in Markdown-ified roxygen and I think it's possible the problem is here. The problem is definitely in the XML produced from the markdown. But there are many things that happen along the way.

I want a bullet list in the description. If I have text right after the list, it gets catenated with the last bullet point. If I add an extra blank line, the text drops out of description and into details.

Here's a pure commonmark example that might explain it. Notice how the text after the bullet list gets absorbed into the bullet item. I tried with both values of `hardbreaks`. Is this correct behaviour?

``` r
library(commonmark)
txt <- "
first line
  * bullet 1
  * bullet 2
second line  
"
txt <- paste0(txt, collapse = "\n")

writeLines(markdown_xml(txt, hardbreaks = FALSE), "hardbreaks-FALSE.xml")
writeLines(markdown_xml(txt, hardbreaks = TRUE), "hardbreaks-TRUE.xml")
```

hardbreaks-FALSE.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <text>first line</text>
  </paragraph>
  <list type="bullet" tight="true">
    <item>
      <paragraph>
        <text>bullet 1</text>
      </paragraph>
    </item>
    <item>
      <paragraph>
        <text>bullet 2</text>
        <softbreak />
        <text>second line</text>
      </paragraph>
    </item>
  </list>
</document>
```

hardbreaks-TRUE.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <text>first line</text>
  </paragraph>
  <list type="bullet" tight="true">
    <item>
      <paragraph>
        <text>bullet 1</text>
      </paragraph>
    </item>
    <item>
      <paragraph>
        <text>bullet 2</text>
        <softbreak />
        <text>second line</text>
      </paragraph>
    </item>
  </list>
</document>

```

**Comment by jeroen** [comment]
Yes commonmark mandates that a list is terminated by a white line. But unfortunately as you point out, a white line in roxygen2 gets preparsed as section split.

One workaround is to insert a white line but explicitly prefix both blocks with a `@description` tag. This seems to work:

```
#' This is the title
#'
#' @description Here begins the description with a list:
#'  - **foo** bla bla
#'  - **bar** bla bla bla
#'  - **baz** blablabla
#'
#' @description Some more description text.
```

Maybe @gaborcsardi has a more elegant solution...

**Comment by jennybc** [comment]
Thanks. It's clear there's no problem in commonmark, then. I'll see whether @gaborcsardi thinks it merits an issue in roxygen2. The workaround is helpful.

**Comment by gaborcsardi** [comment]
I have nothing to add. G

**Comment by hadley** [comment]
We'll make sure to mention this in the upcoming tidyverse style for roxygen page.
