### ISSUE TITLE
Alignment of table cells when converting to XML

### ISSUE THREAD

**Issue by maelle** [r-lib/commonmark#9]
Asking because of my `tinkr` package.

**Comment by maelle** [comment]
When I convert Markdown to XML, the alignment information is lost.

To keep it, I could convert to html instead, but this creates at least one problem: code blocks are transformed to something harder to parse, information seems lost `<pre><code class="language-{r">knitr`.

So for now my package will lose alignment of tables. 

@jeroen do you think there could be a way for `commonmark::markdown_xml` to keep the alignment of cells as an arbitrary attribute?

**Comment by jeroen** [comment]
I think this is fixed in the dev version

**Comment by jeroen** [comment]
No wait it looks like that attribute is not stored in the xml. Hmmm 🤔

**Comment by jeroen** [comment]
I think you should open an issue at the Github cmark repo: https://github.com/github/cmark. It looks like they forgot to encode the alignment attribute in the xml.

**Comment by jeroen** [comment]
This was fixed in commonmark 1.6
